Added docker-compose.yml with excluded Memoryleakfix.
TheStaticVoid/StaTech-Industry pull request #164
Opened 2023-06-02 11:59 UTC by bashbers

See https://github.com/TheStaticVoid/StaTech-Industry/issues/163 for more information as of why this is excluded.

2023-06-02 18:42 UTC, bashbers commented
@TheStaticVoid I tried using the server files as input for the CF_PAGE_URL, but that did not work out as intended. See https://github.com/itzg/docker-minecraft-server/issues/2007#issuecomment-1470550728 for more information on why the docker image author is suggesting to use the client zip in combination with an excluded modlist.

2023-06-03 01:03 UTC, TacoMonkey11 commented
Does this deal with mods which have opted out from third-party downloads? Or is that still a manual responsibility for the user?

2023-06-03 07:15 UTC, bashbers commented
Yes, we are using a Curseforge developer API key.

2023-06-03 10:57 UTC, TacoMonkey11 commented
```
minecraft  | [mc-image-helper] 00:55:26.025 WARN  : The authors of the mod 'Immersive structures' have disallowed project distribution. Manually download the file '[Universal]Immersive Structures-2.0.7a' from https://www.curseforge.com/minecraft/mc-mods/immersive-structures and supply via downloads repo or separately.
```

I don't believe the API key allows third-parties to download those mods which don't allow it. It is still up to the user

2023-06-03 12:31 UTC, TheStaticVoid commented
The API key should allow it. It's blocked on launchers like Prism because we don't have one set.

2023-06-03 15:50 UTC, TheStaticVoid commented
Just ran through the process and also experienced the warning message taco experienced. Not going to be able to merge this unless we find a way to download those as well.

2023-06-03 16:28 UTC, bashbers commented
Ah I did not know that, that sucks.. These mods are just opting out of 3rd-party downloads and there's nothing we can do about that?

2023-06-03 17:23 UTC, TheStaticVoid commented
Not within the CurseForge API

2023-06-03 17:27 UTC, bashbers commented
Looked further into it and came across https://github.com/itzg/docker-minecraft-server/issues/2174

When this is merged into master, then I'll look into making an init-container to download the thirdparty mods! :)

2023-06-03 22:20 UTC, TheStaticVoid commented
I'm not merging to master unless we are able to get those third-party mods as well. If we include as is it would just be more confusing to the user.

2023-06-04 06:03 UTC, bashbers commented
Ah my previous comment might have been confusing. I was referring to the PR I linked, not this PR. The PR I linked is able to solve the third-party mods problem using an init-container, but since it's not merged yet, I would like to wait for any further developments on the PR.

2023-06-04 06:42 UTC, TheStaticVoid commented
Would it be better to download server files from a github release?

2023-06-04 11:18 UTC, TacoMonkey11 commented
> The latest file will be located and used by default, but if a specific version is desired you can use one of the following options. With any of these options do not select a server file -- they lack the required manifest and defeat the ability to consistently automate startup.

https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/curseforge/#usage

2023-06-04 11:39 UTC, bashbers commented
The downloaded server files could work aswell, will look into it.

2023-06-05 00:15 UTC, TacoMonkey11 commented
I reviewed the issue linked in this discussion about init-containers, so I have decided to create one myself, and I have it working rather well.

new contents of docker-compose.yml would be as follows:

```yaml
version: '3'

services:
  cf-initcontainer:
    image: tacomonkey/cf-initcontainer:latest
    container_name: cf-initcontainer
    volumes:
      - "./downloads:/downloads"
    environment:
      - CF_API_KEY=${CF_API_KEY}
      - MODPACK_ID=863689 # project id of the modpack
      - FILE_ID=4566222 #file id of the specific modpack version

  minecraft:
    image: itzg/minecraft-server:java17-graalvm-ce
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - "./mc:/data"
      - "./downloads:/downloads"
    environment:
      - EULA=TRUE
      - MEMORY=8G
      - TYPE=AUTO_CURSEFORGE
      - CF_PAGE_URL=https://www.curseforge.com/minecraft/modpacks/statech-industry
      - CF_API_KEY=${CF_API_KEY}
      - CF_EXCLUDE_MODS=627566 # Disabled Memoryleakfix mod, with this mod the server wouldnt boot. See https://github.com/TheStaticVoid/StaTech-Industry/issues/163
    depends_on:
      cf-initcontainer:
        condition: service_completed_successfully
    tty: true
    stdin_open: true
    restart: always
```

The init-container will start a script which uses the CF API to figure out which mods need to be downloaded, and then forges a download link to use alongside the CF_DOWNLOADS_REPO option in docker-minecraft-server. This may or may not be against curseforge TOS, that is up to interpretation.

2023-06-05 08:47 UTC, bashbers commented
Nicely done, one thing I don't like it the inclusion of your own image. I much rather rely on something generic like a curlcontainer used in the PR I linked.

2023-06-05 17:32 UTC, TacoMonkey11 commented
It seems to be a network issue. If the curl command to query the CF API wasn't silent, it probably would result in an error. I don't actually know what causes this issue, but I believe it may be solved by specifying a different DNS like `8.8.8.8`. I had similar issues on windows.

2023-06-05 17:34 UTC, bashbers commented
This was on a Ubuntu VPS. I think we should make the curl more verbose so we can see more clearly what's going on?

2023-06-05 17:42 UTC, TacoMonkey11 commented
That's a good idea, I can just remove the silent flag from curl.

2023-06-05 19:10 UTC, TheStaticVoid commented
Do we need the FILE_ID now then? Would require updating after a patch to update the id each time.

2023-06-05 19:24 UTC, bashbers commented
The FILE_ID is needed unless we implement a way to get the latest FILE_ID from CF. I would suggest to leave it as is and just update the id once a new version is released. This way people have control over their deployed server version instead of having to rely on the latest version.

2023-06-05 21:13 UTC, TacoMonkey11 commented
@bashbers could you try to run the container again? I've updated the image to now use debian-slim instead of alpine which seems to have fixed the network inconsistencies. The only downside is that the image is now ~47MB instead of 6MB

2023-06-06 09:37 UTC, bashbers commented
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/23037527/48b3bf5a-e11f-4f90-b14b-11ccfad64586)
docker inspect results:

```sh
xxx@xxx:~/minecraft/test# docker inspect tacomonkey/cf-initcontainer
[
    {
        "Id": "sha256:5c8f84ef3c5c380955ebdff8b1f46c3a5821095781783b1ed3e4342fe1f6f11d",
        "RepoTags": [
            "tacomonkey/cf-initcontainer:latest"
        ],
        "RepoDigests": [
            "tacomonkey/cf-initcontainer@sha256:473b1327faf18fea6434a61e07c1827d98df6056b8e912883f511cf95c66431b"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-06-05T21:05:38.0124667Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": {
                "/downloads": {}
            },
            "WorkingDir": "/downloads",
            "Entrypoint": [
                "/bin/bash",
                "/usr/src/find-denied-mods.sh"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 105939178,
        "VirtualSize": 105939178,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/731ed748fbfd63f0390473414047326af7716d4ab5063dcc06d53acb044fc6a1/diff:/var/lib/docker/overlay2/ce109c099c810abcdfafcfafa890d9a3f27fd5ea12a62975023d05d923e11fe7/diff:/var/lib/docker/overlay2/4c26a94e73aeec5df433fc683d623989c9c81465ce2e065d3c7b66c912739f38/diff",
                "MergedDir": "/var/lib/docker/overlay2/ffee31666f36429faef971cb7852b7544cf8b96131bbc26b4d4ea0f195f2e01d/merged",
                "UpperDir": "/var/lib/docker/overlay2/ffee31666f36429faef971cb7852b7544cf8b96131bbc26b4d4ea0f195f2e01d/diff",
                "WorkDir": "/var/lib/docker/overlay2/ffee31666f36429faef971cb7852b7544cf8b96131bbc26b4d4ea0f195f2e01d/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:8e14b8d986dc16da49658ff2abc8e0f0d2760d0e215b385b35e0837da1502bdf",
                "sha256:57ccbfe0778a91fc6a81553838aa2c9b035f4e11adba825b643b366cedb238c5",
                "sha256:d03af2f65d3e00548f18ff6c89d772ee072383c8c4254fed04f262799a314639",
                "sha256:09a08584c6688778bbd222dcba68eec33e3a8cec21cd02b548c58b144f3979da"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

2023-06-06 09:50 UTC, bashbers commented
now the script is crashing on the `mv` commands:

![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/23037527/8ede4fdc-58b4-4a95-a4d5-098f0e258cd2)

2023-06-06 11:39 UTC, TacoMonkey11 commented
This seems rather simple to fix, as everything actually worked correctly, I just need to ignore that "error" by adding `--force` to the `mv` command

2023-06-07 19:40 UTC, TheStaticVoid requested changes
Now that we have something that seems usable let's get the ball rolling.

2023-06-07 19:40 UTC, TheStaticVoid commented on README.md
> +## Server setup using Docker-compose
Keep this section in the README.md. It should link to the Server Setup wiki page where we will include the rest of the sections from this README

2023-06-07 19:40 UTC, TheStaticVoid commented on docker-compose.yml
Update this compose with the latest revision from the discussion

2023-06-07 19:40 UTC, TheStaticVoid commented on .env.example
Did we settle on needing to double the $ signs or no?

2023-06-07 21:55 UTC, TheStaticVoid commented on .env.example
I tested using double $ as well. Would need confirmation from @bashbers

2023-06-08 16:24 UTC, bashbers commented on .env.example
Its really weird, in the cf minecraft container it needs the double `$` but your container does not @TacoMonkey11 .

2023-06-09 22:15 UTC, TacoMonkey11 commented on .env.example
I believe that another issue may be a play then since the API key should not be that inconsistent between users

2023-06-19 22:52 UTC, TacoMonkey11 commented
Since this seems rather stale, I think I will make these changes myself alongside ignoring removing all the other clientside mods.

I'll make a new PR

2023-06-19 23:20 UTC, closed without merging