Peaceful Mode Compat
TheStaticVoid/StaTech-Industry pull request #359
Opened 2023-08-05 18:55 UTC by GW-Dev

As promised, I have come up with recipes that could allow for progression in peaceful mode. 

The recipes were gated to be obtainable roughly when the mob crusher is, except for the Nether Star, as that should be a bit later game.

Recipes added are:
- Nether Star (Assembler)
- Withered Bone (EBF, Cupronickel)
- Spider Eye (Centrifuge)
- Blaze Rod (Chemical Reactor)
- Ghast Tear (Chemical Reactor)
- Rotten Flesh (Chemical Reactor)
- Ender Pearl (Chemical Reactor)

I can also make mob crusher recipes/model textures for phantoms and rabbits.

2023-08-07 17:42 UTC, TheStaticVoid commented
here are my proposed changes to what you're adding:
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/6089108/b294da17-9b08-48d0-90b6-795af5a3e856)
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/6089108/ac80514a-6cc5-4c09-b429-572ac322ab9b)
Changed this to match the existing mod compat. Changing this could cause xp loops
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/6089108/554e22a7-57f5-45f1-a4e3-0fffbbdbaf17)

Spider eyes don't have a recipe.

2023-08-07 17:48 UTC, GW-Dev commented
Spider eyes can be dropped from the witch model.

2023-08-07 18:51 UTC, GW-Dev commented
The revised rotten flesh recipe doesn't work, since players need rotten flesh to make blood.

2023-08-07 20:34 UTC, GW-Dev commented
I meant initially, because the crusher needs blood to run its first recipe. Without the crusher, the only way to get blood is by centrifuging rotten flesh.

2023-08-07 21:14 UTC, TheStaticVoid commented
Ahh true, I would suggest something better than wood tar as the fluid. Sulfuric Acid maybe? idk

2023-08-07 21:16 UTC, GW-Dev commented
Ooh! What about another use for hydrofluoric acid?

2023-08-07 21:18 UTC, TheStaticVoid commented
That could work since it's corrosive and could "melt" flesh

2023-08-08 00:40 UTC, GW-Dev commented
Changes implemented, ready for review

2023-08-08 01:29 UTC, TheStaticVoid requested changes
Everything looks good, just need the blaze rod recipe changed.

2023-08-08 01:29 UTC, TheStaticVoid commented on kubejs/server_scripts/mods/modern_industrialization/chemical_reactor.js
> +            { amount: 1, item: mc('stick') },
change to `mi('steel_rod')`

why? funny -> :trollface: (i think it's more interesting than just a regular stick)

2023-08-08 01:29 UTC, TheStaticVoid commented on kubejs/server_scripts/mods/modern_industrialization/large_chemical_reactor.js
> +            { amount: 4, item: mc('stick') },
Same here

2023-08-08 01:38 UTC, TheStaticVoid approved these changes
Everything looks good

2023-08-08 01:38 UTC, merged